name: Build
on: push
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: knicknic/os-specific-run@v1
        with:
          linux: |
            sudo apt-get update
            sudo apt-get install qemu-system
          macos: "brew install qemu"
          windows: |
            Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
            Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
            scoop bucket add main
            scoop install main/qemu
      - name: qemu
        run: |
          qemu-system-aarch64 --version
